### ISSUE TITLE
Ethernet support

### ISSUE THREAD

**Issue by russss** [willfurnell/esp32-flipdot-controller#2]
I'd like wired ethernet support for using these displays at events. I'm a bit wary of using wifi especially when the ESP32 is in a metal box.

If we're using the ESP32-S3 then it sounds like we need an SPI MAC/PHY for this. The throughput should be pretty minimal so hopefully this won't be an issue.

All the ethernet stuff should be optional.

**Comment by willfurnell** [comment]
I have added this to the schematic
